### ISSUE TITLE
vala-panel.h doesn't exist

### ISSUE THREAD

**Issue by Suzamax** [rilian-la-te/vala-panel-appmenu#72]
When i do `make`, it stucks at 75%, throwing this error:
```
[ 75%] Building C object lib/CMakeFiles/appmenu-valapanel.dir/valapanel-plugin-appmenu.c.o
/home/devel/vala-panel-appmenu-0.4.4/lib/valapanel-plugin-appmenu.c:25:24: error fatal: vala-panel.h: No existe el fichero o el directorio
 #include <vala-panel.h>
                        ^
```
It's 0.4.4

**Comment by rilian-la-te** [comment]
vala-panel version?
```locate vala-panel.h```?

**Comment by Suzamax** [comment]
Vala-panel version is 0.3.52.

Locate vala-panel.h throws no output.

**Comment by rilian-la-te** [comment]
Stable appmenu will not work with series 0.4. Try latest master, please :-)

**Comment by Suzamax** [comment]
I don't use 0.4, I do have 0.3.8.

**Comment by rilian-la-te** [comment]
0.3.8 or 0.3.50? 0.3.50 is 0.4 alpha 1.
If 0.3.8 - will look for it, update will be in 0.3 branch

**Comment by rilian-la-te** [comment]
Fixed in 0.3.9 AFAIK
